# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CD Node.js

on:
  push:
    branches: ['master']

jobs:
  CI_CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/github/cube_web_front
            git pull origin master
            npm ci
            npm run build
            pm2 delete cube-front
            pm2 start "npm run start" --name cube-front
            sudo systemctl reload nginx
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
      # - run: npm ci
      # - run: npm test
      # - run: npm run build
      
